# Generated by Django 2.2.7 on 2020-05-06 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gamesrec.models
import jsonfield.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='D.O.B')),
                ('gender', models.IntegerField(choices=[(0, '-'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=0)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('dislikes', models.ManyToManyField(related_name='c_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='c_likes', to=settings.AUTH_USER_MODEL)),
                ('mention', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mention_user', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='gamesrec.Comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255)),
                ('rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
                ('first_release_date', models.DateTimeField(blank=True, null=True)),
                ('popularity', models.FloatField(default=0.0)),
                ('cover', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-first_release_date'],
            },
        ),
        migrations.CreateModel(
            name='GameListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Playing'), (1, 'Completed'), (2, 'Plan To Play'), (3, 'On Hold'), (4, 'Dropped'), (5, 'Not Interested')], default=0)),
                ('rating', models.IntegerField(choices=[(0, '-'), (1, '1.0'), (2, '1.5'), (3, '2.0'), (4, '2.5'), (5, '3.0'), (6, '3.5'), (7, '4.0'), (8, '4.5'), (9, '5.0'), (10, '5.5'), (11, '6.0'), (12, '6.5'), (13, '7.0'), (14, '7.5'), (15, '8.0'), (16, '8.5'), (17, '9.0'), (18, '9.5'), (19, '10')], default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesrec.Game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GuestRecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Guest Recommendations',
            },
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'User Ratings',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('games', models.ManyToManyField(related_name='websites', to='gamesrec.Game')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('session_key', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('games', models.ManyToManyField(related_name='themes', to='gamesrec.Game')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('image_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesrec.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.IntegerField(choices=[(0, '-'), (1, '1.0'), (2, '1.5'), (3, '2.0'), (4, '2.5'), (5, '3.0'), (6, '3.5'), (7, '4.0'), (8, '4.5'), (9, '5.0'), (10, '5.5'), (11, '6.0'), (12, '6.5'), (13, '7.0'), (14, '7.5'), (15, '8.0'), (16, '8.5'), (17, '9.0'), (18, '9.5'), (19, '10')], default=0)),
                ('char_vis', models.IntegerField(choices=[(0, '-'), (1, '1.0'), (2, '1.5'), (3, '2.0'), (4, '2.5'), (5, '3.0'), (6, '3.5'), (7, '4.0'), (8, '4.5'), (9, '5.0'), (10, '5.5'), (11, '6.0'), (12, '6.5'), (13, '7.0'), (14, '7.5'), (15, '8.0'), (16, '8.5'), (17, '9.0'), (18, '9.5'), (19, '10')], default=0)),
                ('music', models.IntegerField(choices=[(0, '-'), (1, '1.0'), (2, '1.5'), (3, '2.0'), (4, '2.5'), (5, '3.0'), (6, '3.5'), (7, '4.0'), (8, '4.5'), (9, '5.0'), (10, '5.5'), (11, '6.0'), (12, '6.5'), (13, '7.0'), (14, '7.5'), (15, '8.0'), (16, '8.5'), (17, '9.0'), (18, '9.5'), (19, '10')], default=0)),
                ('replay', models.IntegerField(choices=[(0, '-'), (1, '1.0'), (2, '1.5'), (3, '2.0'), (4, '2.5'), (5, '3.0'), (6, '3.5'), (7, '4.0'), (8, '4.5'), (9, '5.0'), (10, '5.5'), (11, '6.0'), (12, '6.5'), (13, '7.0'), (14, '7.5'), (15, '8.0'), (16, '8.5'), (17, '9.0'), (18, '9.5'), (19, '10')], default=0)),
                ('overall', models.IntegerField(choices=[(0, '-'), (1, '1.0'), (2, '1.5'), (3, '2.0'), (4, '2.5'), (5, '3.0'), (6, '3.5'), (7, '4.0'), (8, '4.5'), (9, '5.0'), (10, '5.5'), (11, '6.0'), (12, '6.5'), (13, '7.0'), (14, '7.5'), (15, '8.0'), (16, '8.5'), (17, '9.0'), (18, '9.5'), (19, '10')], default=0)),
                ('spoiler', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('dropped', models.BooleanField(default=False)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesrec.Game')),
                ('helpful_users', models.ManyToManyField(related_name='helpful', to=settings.AUTH_USER_MODEL)),
                ('not_helpful_users', models.ManyToManyField(related_name='unhelpful', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesrec.Game')),
                ('likes', models.ManyToManyField(related_name='rec_likes', to=settings.AUTH_USER_MODEL)),
                ('similar_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similar_game', to='gamesrec.Game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=gamesrec.models.PathAndRename('profile_pictures'))),
                ('display_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('dob_privacy', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=255)),
                ('alternative_name', models.CharField(max_length=255)),
                ('category', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('games', models.ManyToManyField(related_name='platforms', to='gamesrec.Game')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('games', models.ManyToManyField(related_name='player_perspectives', to='gamesrec.Game')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('games', models.ManyToManyField(related_name='genres', to='gamesrec.Game')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('games', models.ManyToManyField(related_name='game_modes', to='gamesrec.Game')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameListItemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Playing'), (1, 'Completed'), (2, 'Plan To Play'), (3, 'On Hold'), (4, 'Dropped'), (5, 'Not Interested')], default=0)),
                ('rating', models.IntegerField(choices=[(0, '-'), (1, '1.0'), (2, '1.5'), (3, '2.0'), (4, '2.5'), (5, '3.0'), (6, '3.5'), (7, '4.0'), (8, '4.5'), (9, '5.0'), (10, '5.5'), (11, '6.0'), (12, '6.5'), (13, '7.0'), (14, '7.5'), (15, '8.0'), (16, '8.5'), (17, '9.0'), (18, '9.5'), (19, '10')], default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_list_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesrec.GameListItem')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('image_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesrec.Game')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesrec.Game')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('rating', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(null=True)),
                ('games', models.ManyToManyField(related_name='age_ratings', to='gamesrec.Game')),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gamesrec.Comment')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesrec.Game')),
            ],
            options={
                'abstract': False,
            },
            bases=('gamesrec.comment',),
        ),
    ]
